#!/usr/bin/env node

/**
 * Generate E2E test stubs for features from the manifest.
 *
 * Usage:
 *   node scripts/e2e/generate-tests.js --feature moc_workflow            # Template stub
 *   node scripts/e2e/generate-tests.js --feature moc_workflow --claude   # Source-aware via Claude CLI
 *   node scripts/e2e/generate-tests.js --auto                            # All missing (template)
 *   node scripts/e2e/generate-tests.js --auto --claude                   # All missing (Claude CLI)
 *   node scripts/e2e/generate-tests.js --auto --json                     # Auto + machine output
 *   node scripts/e2e/generate-tests.js --list                            # List all features
 *   node scripts/e2e/generate-tests.js --from-spec docs/stage-specs/stage-0-capture.md  # From spec doc
 *   node scripts/e2e/generate-tests.js --from-spec all                   # All stage spec docs
 *   node scripts/e2e/generate-tests.js --from-spec all --dry-run         # Preview without writing
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..", "..");
const MANIFEST_PATH = path.resolve(ROOT, "e2e", "state", "manifest.json");
const TESTS_DIR = path.resolve(ROOT, "e2e", "tests", "features");
const EXAMPLE_SPEC = path.resolve(ROOT, "e2e", "tests", "personas", "ace-actionitem.spec.ts");
const PERSONAS_FILE = path.resolve(ROOT, "e2e", "fixtures", "personas.ts");
const PROMPT_FILE = path.resolve(ROOT, "e2e", "state", "gen-test-prompt.md");
const STAGE_SPECS_DIR = path.resolve(ROOT, "docs", "stage-specs");
const SPEC_TESTS_DIR = path.resolve(ROOT, "e2e", "tests", "spec-compliance");

function loadManifest() {
  return JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf-8"));
}

function generateSpecContent(featureKey) {
  return `/**
 * ${featureKey} — Auto-generated feature persona test
 *
 * Tests permissions, page access, and denial for all personas
 * mapped to this feature in manifest.json.
 *
 * Generated by: node scripts/e2e/generate-tests.js --feature ${featureKey}
 */

import { describeFeaturePersonaTests } from "../../templates/feature-persona.template";

describeFeaturePersonaTests("${featureKey}");
`;
}

// ---------------------------------------------------------------------------
// Claude CLI source-aware generation
// ---------------------------------------------------------------------------

/**
 * Check if Claude CLI is available.
 */
function isClaudeAvailable() {
  try {
    execSync("claude --version", { stdio: "pipe", timeout: 5000 });
    return true;
  } catch {
    return false;
  }
}

/**
 * Read first N lines of a file (or all if fewer lines).
 */
function readFirstLines(filePath, maxLines) {
  try {
    const content = fs.readFileSync(filePath, "utf-8");
    const lines = content.split("\n");
    return lines.slice(0, maxLines).join("\n");
  } catch {
    return null;
  }
}

/**
 * Resolve page paths from manifest to actual source files in the app/ directory.
 * e.g., "/admin/people" -> "app/admin/people/page.tsx"
 */
function resolvePageSourceFiles(pages) {
  const sources = [];
  for (const pagePath of pages) {
    // Skip wildcard pages like /mocs/*/hotspots
    if (pagePath.includes("*")) {
      continue;
    }

    // Convert URL path to file path: /admin/people -> app/admin/people/page.tsx
    const cleaned = pagePath.replace(/^\//, "");
    const candidates = [
      path.join(ROOT, "app", cleaned, "page.tsx"),
      path.join(ROOT, "app", cleaned, "page.ts"),
      // Dynamic routes: /mocs/[id] -> app/mocs/[id]/page.tsx
      path.join(ROOT, "app", cleaned.replace(/\/[^/]+$/, "/[id]"), "page.tsx"),
    ];

    for (const candidate of candidates) {
      if (fs.existsSync(candidate)) {
        const relativePath = path.relative(ROOT, candidate).replace(/\\/g, "/");
        const content = readFirstLines(candidate, 300);
        if (content) {
          sources.push({ path: relativePath, content });
        }
        break;
      }
    }
  }
  return sources;
}

/**
 * Find the persona constant names from personas.ts for a list of persona IDs.
 * e.g., "cliff-patience" -> "CLIFF_PATIENCE"
 *
 * Uses line-based search instead of regex to avoid Node.js string escaping issues.
 */
function resolvePersonaConstants(personaIds) {
  try {
    const lines = fs.readFileSync(PERSONAS_FILE, "utf-8").split("\n");
    const results = [];
    const idSet = new Set(personaIds);

    // Scan lines: when we find `export const X: Persona`, remember the const name.
    // When we find `id: "some-id"` within the next few lines, map it.
    let lastConstName = null;
    let lastConstLine = -1;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      // Match: export const CLIFF_PATIENCE: Persona = {
      const constMatch = line.match(/export\s+const\s+(\w+)\s*:\s*Persona/);
      if (constMatch) {
        lastConstName = constMatch[1];
        lastConstLine = i;
        continue;
      }

      // Match: id: "cliff-patience",
      if (lastConstName && i - lastConstLine <= 5) {
        const idMatch = line.match(/id:\s*"([^"]+)"/);
        if (idMatch && idSet.has(idMatch[1])) {
          results.push({ id: idMatch[1], constName: lastConstName });
          idSet.delete(idMatch[1]);
          lastConstName = null;
        }
      }
    }
    return results;
  } catch {
    return [];
  }
}

/**
 * Build the Claude prompt for source-aware test generation.
 */
function buildClaudePrompt(featureKey, feature) {
  const pageSourceFiles = resolvePageSourceFiles(feature.pages || []);
  const personaConstants = resolvePersonaConstants(feature.personas || []);

  // Read example spec (first 100 lines)
  const exampleSpec = readFirstLines(EXAMPLE_SPEC, 100) || "(example spec not found)";

  // Build page source section
  let pageSourceSection = "";
  if (pageSourceFiles.length > 0) {
    pageSourceSection = "\n## Actual page source files\n\n";
    for (const src of pageSourceFiles) {
      pageSourceSection += `### ${src.path}\n\`\`\`tsx\n${src.content}\n\`\`\`\n\n`;
    }
  } else {
    pageSourceSection =
      "\n## Page source files\n\nNo directly-mapped page files found. " +
      "Generate tests based on the code areas and permissions listed above.\n\n";
  }

  // Build persona imports section
  let personaImports = "";
  let personaList = "";
  if (personaConstants.length > 0) {
    personaImports = personaConstants.map((p) => p.constName).join(", ");
    personaList = personaConstants
      .map((p) => `- \`${p.constName}\` (id: "${p.id}")`)
      .join("\n");
  }

  const prompt = `You are generating a Playwright E2E test file for the ChangePilot (MOC-AI) application.

## Feature: ${featureKey}

### Manifest entry
\`\`\`json
${JSON.stringify(feature, null, 2)}
\`\`\`

### Persona constants to import
${personaList || "(no matching persona constants found — use persona IDs as reference)"}

### Permissions tested by this feature
${(feature.permissions || []).map((p) => `- \`${p}\``).join("\n")}

### Pages to test
${(feature.pages || []).map((p) => `- ${p}`).join("\n") || "(no pages listed — focus on API/permission tests)"}

### Code areas
${(feature.codeAreas || []).map((p) => `- ${p}`).join("\n") || "(none)"}
${pageSourceSection}
## Example spec file (ace-actionitem.spec.ts, first 100 lines)

\`\`\`typescript
${exampleSpec}
\`\`\`

## Test fixture API reference

The \`sim\` fixture (SimulationManager) provides these key methods:

- \`await sim.loginAsDeveloper()\` — Log in as the pool developer account (call in beforeEach)
- \`await sim.simulateAs(PERSONA)\` — Start simulation as a persona (call in beforeEach after login)
- \`await sim.swapTo(persona)\` — Swap to a different persona role mid-test (lightweight, no re-login)
- \`await sim.goto(path)\` — Navigate to a page path (e.g., "/mocs")
- \`await sim.tryAccessPage(path)\` — Navigate and return { status, redirected } for access checks
- \`await sim.evaluatePage()\` — Run oracle validation on the current page, returns { passed, ... }
- \`await sim.validatePageWithOracle(path)\` — Combined goto + oracle validation
- \`await sim.screenshot(name)\` — Take a named screenshot
- \`sim.reportFinding({ severity, page, description })\` — Report a test finding
- \`sim.recordPass()\` — Record a passing check for green tracker
- \`sim.getPage()\` — Get the underlying Playwright Page object

Severity levels: "bug", "ux", "security", "inconsistency", "suggestion", "product"

## Instructions

Generate a complete TypeScript Playwright test file for the \`${featureKey}\` feature. Follow these rules exactly:

1. **Imports**: Use \`import { test, expect } from "../../fixtures/test";\` and import persona constants from \`"../../fixtures/personas"\`.
${personaImports ? `   Import: \`{ ${personaImports} }\`` : "   (define inline persona objects if no constants are available)"}

2. **Structure**: Use \`test.describe("Feature Name", () => { ... })\` with \`test.beforeEach\` that calls \`sim.loginAsDeveloper()\` and \`sim.simulateAs(PRIMARY_PERSONA)\`.

3. **Page access tests**: For each page in the manifest, test that:
   - Allowed personas can access the page (status < 400, not redirected to /login)
   - Use \`sim.tryAccessPage(path)\` and check \`result.status\` and \`result.redirected\`
   - Take screenshots with \`sim.screenshot()\`

4. **Source-aware UI tests**: If page source is provided above, write tests that check for ACTUAL elements visible in the source code:
   - Look for heading text, button labels, tab names, section headers in the source
   - Use \`page.locator()\` or \`page.getByRole()\` or \`page.getByText()\` to assert they exist
   - Do NOT guess or invent UI elements — only test what appears in the source

5. **Permission boundary tests**: For personas that should NOT have access (lower roles), verify they get denied:
   - Use \`sim.swapTo()\` to change to a restricted persona
   - Verify redirect or 403/401

6. **Error handling**: Wrap oracle/screenshot calls in try/catch or use \`.catch(() => {})\` — these are best-effort.

7. **Findings**: Use \`sim.reportFinding()\` when unexpected access is granted or denied.

8. **Output**: Return ONLY the TypeScript file content. No markdown fences, no explanation — just the raw .ts file content.

Generate the test file now:`;

  return prompt;
}

/**
 * Invoke Claude CLI to generate a source-aware test file.
 * Returns the generated content string, or null on failure.
 */
function generateWithClaude(featureKey, feature) {
  const prompt = buildClaudePrompt(featureKey, feature);

  // Write prompt to temp file to avoid shell escaping issues
  fs.writeFileSync(PROMPT_FILE, prompt);

  const model = process.env.TESTGEN_MODEL || "haiku";
  const budget = process.env.TESTGEN_BUDGET || "0.20";

  try {
    const result = execSync(
      `claude --print --dangerously-skip-permissions --model ${model} --max-budget-usd ${budget} < "${PROMPT_FILE}"`,
      {
        cwd: ROOT,
        stdio: ["pipe", "pipe", "pipe"],
        timeout: 120000, // 2 minutes per generation
        env: {
          ...process.env,
          CLAUDE_CODE_ENTRYPOINT: "generate-tests",
          // Unset nesting guard so Claude CLI can launch from within a Claude Code session
          CLAUDECODE: "",
          CLAUDE_CODE: "",
        },
      }
    );

    // Clean up prompt file
    try {
      fs.unlinkSync(PROMPT_FILE);
    } catch {
      /* ignore */
    }

    let output = result.toString().trim();

    // Token accounting
    try {
      const _tl = require("./lib/token-logger");
      const _modelUsed = process.env.TESTGEN_MODEL || "haiku";
      const _inEst = Math.ceil((fs.existsSync(PROMPT_FILE) ? fs.statSync(PROMPT_FILE).size : 0) / 4);
      const _outEst = Math.ceil(output.length / 4);
      _tl.logTokenUsage({ component: "generate-tests", inputTokens: _inEst, outputTokens: _outEst, provider: "claude", model: _modelUsed });
    } catch { /* non-fatal */ }

    // Strip markdown fences if Claude wrapped the output
    if (output.startsWith("```typescript")) {
      output = output.replace(/^```typescript\s*\n/, "").replace(/\n```\s*$/, "");
    } else if (output.startsWith("```ts")) {
      output = output.replace(/^```ts\s*\n/, "").replace(/\n```\s*$/, "");
    } else if (output.startsWith("```")) {
      output = output.replace(/^```\s*\n/, "").replace(/\n```\s*$/, "");
    }

    // Basic validation: must contain fixture import and at least one test
    if (
      !output.includes('from "../../fixtures/test"') ||
      !output.includes("test(") ||
      !output.includes("test.describe(")
    ) {
      console.error(
        `  Claude output failed validation (missing fixture import or test blocks). Falling back to template.`
      );
      return null;
    }

    return output + "\n";
  } catch (err) {
    const stderr = (err.stderr || "").toString().slice(-300);
    const stdout = (err.stdout || "").toString().slice(-300);
    console.error(`  Claude CLI failed: ${stderr || stdout || err.message}`);

    // Clean up prompt file
    try {
      fs.unlinkSync(PROMPT_FILE);
    } catch {
      /* ignore */
    }

    return null;
  }
}

// ---------------------------------------------------------------------------
// Parse args
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const getArg = (name) => {
  const idx = args.indexOf(name);
  return idx === -1 ? null : args[idx + 1] || null;
};
const hasFlag = (name) => args.includes(name);

const manifest = loadManifest();
const JSON_MODE = hasFlag("--json");
const CLAUDE_MODE = hasFlag("--claude");

// ---------------------------------------------------------------------------
// --list: Show all features
// ---------------------------------------------------------------------------
if (hasFlag("--list")) {
  console.log("Features in manifest.json:\n");
  for (const [key, feat] of Object.entries(manifest.features)) {
    const slug = key.replace(/_/g, "-");
    const specPath = path.join(TESTS_DIR, `${slug}.spec.ts`);
    const hasTest = fs.existsSync(specPath);
    console.log(`  ${hasTest ? "[x]" : "[ ]"} ${key}`);
    console.log(`      Personas: ${feat.personas.join(", ")}`);
    console.log(`      Permissions: ${feat.permissions.length}`);
    console.log(`      Pages: ${feat.pages.join(", ") || "(none)"}`);
    console.log();
  }
  process.exit(0);
}

// ---------------------------------------------------------------------------
// --from-spec: Generate tests from per-stage spec documents
// ---------------------------------------------------------------------------
if (hasFlag("--from-spec")) {
  const specArg = getArg("--from-spec");
  const DRY_RUN = hasFlag("--dry-run");

  if (!specArg) {
    console.error("Usage: --from-spec <path|all> [--dry-run] [--claude]");
    process.exit(1);
  }

  /**
   * Parse a stage spec document into structured requirements.
   */
  function parseStageSpec(filePath) {
    const content = fs.readFileSync(filePath, "utf-8");
    const fileName = path.basename(filePath);
    const stageMatch = fileName.match(/stage-(\d+)/i);
    const stageNum = stageMatch ? parseInt(stageMatch[1], 10) : null;

    const spec = {
      file: fileName,
      stage: stageNum,
      title: "",
      mandatoryFields: [],
      entryCriteria: [],
      exitCriteria: [],
      validations: [],
      uxRequirements: [],
      auditEvents: [],
      stateTransitions: [],
      knownIssues: [],
    };

    let currentSection = null;
    let inEntry = false;
    let inExit = false;

    for (const line of content.split("\n")) {
      // Title
      const titleMatch = line.match(/^#\s+(.+)/);
      if (titleMatch && !spec.title) {
        spec.title = titleMatch[1].trim();
        continue;
      }

      // Section headers
      const sectionMatch = line.match(/^##\s+(.+)/i);
      if (sectionMatch) {
        const heading = sectionMatch[1].toLowerCase();
        if (heading.includes("mandatory") || heading.includes("field")) {
          currentSection = "fields";
        } else if (heading.includes("entry") || heading.includes("exit")) {
          currentSection = "criteria";
        } else if (heading.includes("workflow") || heading.includes("state")) {
          currentSection = "states";
        } else if (heading.includes("visual") || heading.includes("ux")) {
          currentSection = "ux";
        } else if (heading.includes("audit")) {
          currentSection = "audit";
        } else if (heading.includes("known") || heading.includes("issue")) {
          currentSection = "issues";
        } else {
          currentSection = heading;
        }
        inEntry = heading.includes("can enter") || heading.includes("entry");
        inExit = heading.includes("can advance") || heading.includes("exit");
        continue;
      }

      // Sub-headers for entry/exit criteria
      const subMatch = line.match(/^\*\*(.+)\*\*/);
      if (subMatch && currentSection === "criteria") {
        const sub = subMatch[1].toLowerCase();
        inEntry = sub.includes("can enter") || sub.includes("entry");
        inExit = sub.includes("can advance") || sub.includes("exit");
      }

      // Table rows (mandatory fields, validations)
      if (currentSection === "fields" && line.startsWith("|") && !line.match(/^\|[\s-|]+\|$/)) {
        const cells = line.split("|").map((c) => c.trim()).filter(Boolean);
        if (cells.length >= 3 && cells[0] !== "Field" && cells[0] !== "---") {
          spec.mandatoryFields.push({
            field: cells[0],
            type: cells[1] || "",
            required: (cells[2] || "").toLowerCase().includes("yes"),
            validation: cells[3] || "",
            smeIntent: cells[4] || "",
          });
          if (cells[3] && cells[3] !== "--") {
            spec.validations.push({ field: cells[0], rule: cells[3] });
          }
        }
        continue;
      }

      // Checklist items (entry/exit criteria)
      const checkMatch = line.match(/^-\s+\[([x ])\]\s+(.+)/i);
      if (checkMatch && currentSection === "criteria") {
        const item = { text: checkMatch[2].trim(), checked: checkMatch[1] === "x" };
        if (inEntry) {
          spec.entryCriteria.push(item);
        } else if (inExit) {
          spec.exitCriteria.push(item);
        }
        continue;
      }

      // Bullet items in other sections
      const bulletMatch = line.match(/^-\s+(.+)/);
      if (bulletMatch) {
        if (currentSection === "ux") {
          spec.uxRequirements.push(bulletMatch[1].trim());
        } else if (currentSection === "audit") {
          spec.auditEvents.push(bulletMatch[1].trim());
        } else if (currentSection === "states") {
          spec.stateTransitions.push(bulletMatch[1].trim());
        } else if (currentSection === "issues") {
          spec.knownIssues.push(bulletMatch[1].trim());
        }
      }
    }

    return spec;
  }

  /**
   * Find which manifest features map to a given stage.
   */
  function findFeaturesForStage(stageNum) {
    const stagePrefix = `stage_${stageNum}`;
    const matched = [];
    for (const [key, feat] of Object.entries(manifest.features)) {
      const hasStagePermission = (feat.permissions || []).some((p) => p.startsWith(stagePrefix));
      const hasStageCodeArea = (feat.codeAreas || []).some(
        (a) => a.includes(`/stage-${stageNum}`) || a.includes(`/stage${stageNum}`)
      );
      // Also match by feature key naming convention
      const stageNames = ["moc_workflow", "moc_frame", "moc_hotspots", "moc_route", "moc_review", "moc_execute", "moc_closeout"];
      const isStageFeature = key === stageNames[stageNum];
      if (hasStagePermission || hasStageCodeArea || isStageFeature) {
        matched.push({ key, feature: feat });
      }
    }
    return matched;
  }

  /**
   * Find existing test files that cover a stage's requirements.
   */
  function findExistingCoverage(stageNum) {
    const coverage = { specTests: [], featureTests: [], personaTests: [] };

    // Check spec-compliance tests
    if (fs.existsSync(SPEC_TESTS_DIR)) {
      const files = fs.readdirSync(SPEC_TESTS_DIR).filter((f) => f.includes(`stage-${stageNum}`) && f.endsWith(".spec.ts"));
      coverage.specTests = files;
    }

    // Check feature tests
    if (fs.existsSync(TESTS_DIR)) {
      const stageNames = ["moc-workflow", "moc-frame", "moc-hotspots", "moc-route", "moc-review", "moc-execute", "moc-closeout"];
      const slug = stageNames[stageNum];
      if (slug) {
        const featureSpec = path.join(TESTS_DIR, `${slug}.spec.ts`);
        if (fs.existsSync(featureSpec)) {
          coverage.featureTests.push(`${slug}.spec.ts`);
        }
      }
    }

    return coverage;
  }

  /**
   * Build a Claude prompt specifically for spec-driven test generation.
   */
  function buildSpecTestPrompt(spec, stageFeatures, existingCoverage) {
    const exampleSpec = readFirstLines(EXAMPLE_SPEC, 100) || "(not found)";

    // Collect page source files from all stage features
    const allPages = [];
    const allPersonas = [];
    for (const { feature } of stageFeatures) {
      allPages.push(...(feature.pages || []));
      allPersonas.push(...(feature.personas || []));
    }
    const uniquePages = [...new Set(allPages)];
    const uniquePersonas = [...new Set(allPersonas)];

    const pageSourceFiles = resolvePageSourceFiles(uniquePages);
    const personaConstants = resolvePersonaConstants(uniquePersonas);

    let prompt = `You are generating Playwright E2E tests from a BUILD-SPEC compliance document for ChangePilot.

## Spec Document: ${spec.title || spec.file}
Stage: ${spec.stage}

`;

    // Mandatory fields
    if (spec.mandatoryFields.length > 0) {
      prompt += `### Mandatory Fields & Validations\n\n`;
      prompt += `| Field | Type | Required | Validation |\n|---|---|---|---|\n`;
      for (const f of spec.mandatoryFields) {
        prompt += `| ${f.field} | ${f.type} | ${f.required ? "yes" : "no"} | ${f.validation} |\n`;
      }
      prompt += `\n`;
    }

    // Entry/exit criteria
    if (spec.entryCriteria.length > 0) {
      prompt += `### Entry Criteria\n`;
      for (const c of spec.entryCriteria) {
        prompt += `- [${c.checked ? "x" : " "}] ${c.text}\n`;
      }
      prompt += `\n`;
    }
    if (spec.exitCriteria.length > 0) {
      prompt += `### Exit Criteria (advance to next stage)\n`;
      for (const c of spec.exitCriteria) {
        prompt += `- [${c.checked ? "x" : " "}] ${c.text}\n`;
      }
      prompt += `\n`;
    }

    // State transitions
    if (spec.stateTransitions.length > 0) {
      prompt += `### Workflow State Transitions\n`;
      for (const s of spec.stateTransitions) {
        prompt += `- ${s}\n`;
      }
      prompt += `\n`;
    }

    // UX requirements
    if (spec.uxRequirements.length > 0) {
      prompt += `### Visual & UX Requirements\n`;
      for (const u of spec.uxRequirements) {
        prompt += `- ${u}\n`;
      }
      prompt += `\n`;
    }

    // Audit events
    if (spec.auditEvents.length > 0) {
      prompt += `### Audit Trail Events\n`;
      for (const a of spec.auditEvents) {
        prompt += `- ${a}\n`;
      }
      prompt += `\n`;
    }

    // Manifest features for this stage
    prompt += `### Related Manifest Features\n\n`;
    for (const { key, feature } of stageFeatures) {
      prompt += `**${key}**: permissions=[${(feature.permissions || []).join(", ")}], pages=[${(feature.pages || []).join(", ")}]\n`;
    }
    prompt += `\n`;

    // Personas
    if (personaConstants.length > 0) {
      prompt += `### Persona Constants to Import\n`;
      for (const p of personaConstants) {
        prompt += `- \`${p.constName}\` (id: "${p.id}")\n`;
      }
      prompt += `\n`;
    }

    // Page source
    if (pageSourceFiles.length > 0) {
      prompt += `### Page Source Files\n\n`;
      for (const src of pageSourceFiles.slice(0, 3)) {
        prompt += `#### ${src.path}\n\`\`\`tsx\n${src.content}\n\`\`\`\n\n`;
      }
    }

    // Existing coverage
    const allExisting = [...existingCoverage.specTests, ...existingCoverage.featureTests, ...existingCoverage.personaTests];
    if (allExisting.length > 0) {
      prompt += `### Existing Test Coverage (DO NOT duplicate)\n`;
      for (const t of allExisting) {
        prompt += `- ${t}\n`;
      }
      prompt += `\n`;
    }

    // Example
    prompt += `### Example spec file (first 100 lines)\n\`\`\`typescript\n${exampleSpec}\n\`\`\`\n\n`;

    // Fixture API
    prompt += `## Test fixture API reference

The \`sim\` fixture (SimulationManager) provides:
- \`await sim.loginAsDeveloper()\` — Log in as pool developer
- \`await sim.simulateAs(PERSONA)\` — Start simulation as persona
- \`await sim.swapTo(persona)\` — Swap role mid-test
- \`await sim.goto(path)\` — Navigate to page
- \`await sim.tryAccessPage(path)\` — Navigate and return { status, redirected }
- \`await sim.evaluatePage()\` — Oracle validation on current page
- \`await sim.screenshot(name)\` — Take screenshot
- \`sim.reportFinding({ severity, page, description })\` — Report finding
- \`sim.recordPass()\` — Record passing check
- \`sim.getPage()\` — Get Playwright Page object

`;

    // Instructions
    prompt += `## Instructions

Generate a Playwright test file that validates the SPEC REQUIREMENTS above. Focus on:

1. **Field validation tests**: For each mandatory field, test that:
   - Required fields cannot be empty (form rejects submission)
   - Validation rules are enforced (min length, format, etc.)

2. **Entry/exit criteria tests**: For each criterion:
   - Entry criteria: verify the stage blocks access when criteria aren't met
   - Exit criteria: verify the stage blocks advancement when criteria aren't met

3. **State transition tests**: Verify valid transitions work and invalid transitions are blocked

4. **UX requirement tests**: Check that required UI elements exist, correct labels/buttons shown

5. **Audit trail tests**: Verify that actions create expected audit records

6. **Permission boundary tests**: Use sim.swapTo() to verify role-based access

**Imports**: Use \`import { test, expect } from "../../fixtures/test";\`
${personaConstants.length > 0 ? `Import personas: \`{ ${personaConstants.map((p) => p.constName).join(", ")} }\` from \`"../../fixtures/personas"\`` : ""}

**File structure**: Use \`test.describe("Stage ${spec.stage}: ${spec.title}", () => { ... })\`

**Output**: Return ONLY the TypeScript file content. No markdown fences, no explanation.

Generate the test file now:`;

    return prompt;
  }

  /**
   * Generate spec-compliance test via Claude CLI.
   */
  function generateSpecTest(spec, stageFeatures, existingCoverage) {
    const prompt = buildSpecTestPrompt(spec, stageFeatures, existingCoverage);

    if (!isClaudeAvailable()) {
      console.log("  Claude CLI not available. Cannot generate spec tests without Claude.");
      return null;
    }

    fs.writeFileSync(PROMPT_FILE, prompt);

    const model = process.env.TESTGEN_MODEL || "sonnet";
    const budget = process.env.TESTGEN_BUDGET || "0.50";

    try {
      const result = execSync(
        `claude --print --dangerously-skip-permissions --model ${model} --max-budget-usd ${budget} < "${PROMPT_FILE}"`,
        {
          cwd: ROOT,
          stdio: ["pipe", "pipe", "pipe"],
          timeout: 180000,
          env: {
            ...process.env,
            CLAUDE_CODE_ENTRYPOINT: "generate-tests-from-spec",
            CLAUDECODE: "",
            CLAUDE_CODE: "",
          },
        }
      );

      try {
        fs.unlinkSync(PROMPT_FILE);
      } catch { /* ignore */ }

      let output = result.toString().trim();

      // Token accounting
      try {
        const _tl = require("./lib/token-logger");
        const _modelUsed = process.env.TESTGEN_MODEL || "sonnet";
        const _inEst = Math.ceil((fs.existsSync(PROMPT_FILE) ? fs.statSync(PROMPT_FILE).size : 0) / 4);
        const _outEst = Math.ceil(output.length / 4);
        _tl.logTokenUsage({ component: "generate-tests", inputTokens: _inEst, outputTokens: _outEst, provider: "claude", model: _modelUsed });
      } catch { /* non-fatal */ }

      // Strip markdown fences
      if (output.startsWith("```typescript")) {
        output = output.replace(/^```typescript\s*\n/, "").replace(/\n```\s*$/, "");
      } else if (output.startsWith("```ts")) {
        output = output.replace(/^```ts\s*\n/, "").replace(/\n```\s*$/, "");
      } else if (output.startsWith("```")) {
        output = output.replace(/^```\s*\n/, "").replace(/\n```\s*$/, "");
      }

      // Validate
      if (!output.includes('from "../../fixtures/test"') || !output.includes("test(")) {
        console.error("  Claude output failed validation. Skipping.");
        return null;
      }

      return output + "\n";
    } catch (err) {
      const stderr = (err.stderr || "").toString().slice(-300);
      console.error(`  Claude CLI failed: ${stderr || err.message}`);
      try {
        fs.unlinkSync(PROMPT_FILE);
      } catch { /* ignore */ }
      return null;
    }
  }

  /**
   * Generate a template test (no Claude) from spec requirements.
   */
  function generateSpecTemplate(spec) {
    const lines = [
      `/**`,
      ` * Stage ${spec.stage} Spec Compliance Tests`,
      ` *`,
      ` * Auto-generated from: ${spec.file}`,
      ` * Generated by: node scripts/e2e/generate-tests.js --from-spec ${spec.file}`,
      ` */`,
      ``,
      `import { test, expect } from "../../fixtures/test";`,
      ``,
      `test.describe("Stage ${spec.stage}: Spec Compliance", () => {`,
      `  test.beforeEach(async ({ sim }) => {`,
      `    await sim.loginAsDeveloper();`,
      `  });`,
      ``,
    ];

    // Field validation tests
    if (spec.mandatoryFields.length > 0) {
      lines.push(`  test.describe("Mandatory Fields", () => {`);
      for (const f of spec.mandatoryFields) {
        if (f.required) {
          lines.push(`    test("${f.field} is required", async ({ sim }) => {`);
          lines.push(`      // TODO: Navigate to stage ${spec.stage}, attempt submit without ${f.field}`);
          lines.push(`      // Verify validation error is shown`);
          lines.push(`    });`);
          lines.push(``);
        }
        if (f.validation && f.validation !== "--") {
          lines.push(`    test("${f.field} validates: ${f.validation.replace(/"/g, "'")}", async ({ sim }) => {`);
          lines.push(`      // TODO: Enter invalid value for ${f.field}, verify rejection`);
          lines.push(`    });`);
          lines.push(``);
        }
      }
      lines.push(`  });`);
      lines.push(``);
    }

    // Entry criteria tests
    if (spec.entryCriteria.length > 0) {
      lines.push(`  test.describe("Entry Criteria", () => {`);
      for (const c of spec.entryCriteria) {
        lines.push(`    test("entry: ${c.text.replace(/"/g, "'").slice(0, 80)}", async ({ sim }) => {`);
        lines.push(`      // TODO: Verify this entry criterion is enforced`);
        lines.push(`    });`);
        lines.push(``);
      }
      lines.push(`  });`);
      lines.push(``);
    }

    // Exit criteria tests
    if (spec.exitCriteria.length > 0) {
      lines.push(`  test.describe("Exit Criteria", () => {`);
      for (const c of spec.exitCriteria) {
        lines.push(`    test("exit: ${c.text.replace(/"/g, "'").slice(0, 80)}", async ({ sim }) => {`);
        lines.push(`      // TODO: Verify this exit criterion is enforced before stage advance`);
        lines.push(`    });`);
        lines.push(``);
      }
      lines.push(`  });`);
      lines.push(``);
    }

    // UX requirement tests
    if (spec.uxRequirements.length > 0) {
      lines.push(`  test.describe("UX Requirements", () => {`);
      for (let i = 0; i < Math.min(spec.uxRequirements.length, 10); i++) {
        const req = spec.uxRequirements[i];
        lines.push(`    test("ux: ${req.replace(/"/g, "'").slice(0, 80)}", async ({ sim }) => {`);
        lines.push(`      // TODO: Verify this UX requirement`);
        lines.push(`    });`);
        lines.push(``);
      }
      lines.push(`  });`);
      lines.push(``);
    }

    lines.push(`});`);
    lines.push(``);

    return lines.join("\n");
  }

  // Collect spec files
  let specFiles = [];
  if (specArg === "all") {
    if (!fs.existsSync(STAGE_SPECS_DIR)) {
      console.log(`No stage spec files found in ${STAGE_SPECS_DIR}`);
      console.log("Drop your spec docs there and re-run.");
      process.exit(0);
    }
    specFiles = fs.readdirSync(STAGE_SPECS_DIR)
      .filter((f) => f.match(/^stage-\d+/) && f.endsWith(".md"))
      .map((f) => path.join(STAGE_SPECS_DIR, f));
  } else {
    const resolved = path.resolve(specArg);
    if (!fs.existsSync(resolved)) {
      console.error(`Spec file not found: ${resolved}`);
      process.exit(1);
    }
    specFiles = [resolved];
  }

  if (specFiles.length === 0) {
    console.log("No stage spec files found matching stage-N-*.md pattern.");
    console.log(`Expected location: ${STAGE_SPECS_DIR}/`);
    console.log("File naming: stage-0-capture.md, stage-1-frame.md, etc.");
    process.exit(0);
  }

  // Process each spec
  fs.mkdirSync(SPEC_TESTS_DIR, { recursive: true });
  const results = { processed: 0, created: [], skipped: [], errors: [] };

  for (const specFile of specFiles) {
    results.processed++;
    const spec = parseStageSpec(specFile);
    const stageFeatures = findFeaturesForStage(spec.stage);
    const existingCoverage = findExistingCoverage(spec.stage);

    const reqCount = spec.mandatoryFields.length + spec.entryCriteria.length +
      spec.exitCriteria.length + spec.uxRequirements.length + spec.auditEvents.length;

    console.log(`\n[from-spec] ${spec.file} — Stage ${spec.stage}`);
    console.log(`  Requirements: ${reqCount} (${spec.mandatoryFields.length} fields, ${spec.entryCriteria.length} entry, ${spec.exitCriteria.length} exit, ${spec.uxRequirements.length} ux, ${spec.auditEvents.length} audit)`);
    console.log(`  Manifest features: ${stageFeatures.map((f) => f.key).join(", ") || "(none)"}`);
    console.log(`  Existing tests: ${[...existingCoverage.specTests, ...existingCoverage.featureTests].join(", ") || "(none)"}`);

    if (reqCount === 0) {
      console.log("  Skipped — no extractable requirements.");
      results.skipped.push(spec.file);
      continue;
    }

    const testSlug = `stage-${spec.stage}-compliance`;
    const testPath = path.join(SPEC_TESTS_DIR, `${testSlug}.spec.ts`);

    if (fs.existsSync(testPath) && !hasFlag("--force")) {
      console.log(`  Skipped — ${testSlug}.spec.ts already exists. Use --force to overwrite.`);
      results.skipped.push(spec.file);
      continue;
    }

    if (DRY_RUN) {
      console.log(`  [dry-run] Would create: e2e/tests/spec-compliance/${testSlug}.spec.ts`);
      results.created.push(spec.file);
      continue;
    }

    let content;
    if (CLAUDE_MODE) {
      console.log("  Generating via Claude CLI...");
      content = generateSpecTest(spec, stageFeatures, existingCoverage);
    }
    if (!content) {
      content = generateSpecTemplate(spec);
      console.log("  Generated template test (use --claude for source-aware generation).");
    } else {
      console.log("  Generated source-aware test via Claude.");
    }

    fs.writeFileSync(testPath, content);
    console.log(`  Created: e2e/tests/spec-compliance/${testSlug}.spec.ts`);
    results.created.push(spec.file);
  }

  // Summary
  console.log(`\n=== From-Spec Results ===`);
  console.log(`Processed: ${results.processed}`);
  console.log(`Created: ${results.created.length}`);
  console.log(`Skipped: ${results.skipped.length}`);
  if (results.created.length > 0 && !DRY_RUN) {
    console.log(`\nRun: cd e2e && npx playwright test tests/spec-compliance/`);
  }
  process.exit(0);
}

// ---------------------------------------------------------------------------
// Helper: generate a spec file for a feature (template or Claude)
// ---------------------------------------------------------------------------
function generateSpec(featureKey) {
  if (CLAUDE_MODE) {
    const feature = manifest.features[featureKey];
    if (!feature) {
      return generateSpecContent(featureKey);
    }

    if (!isClaudeAvailable()) {
      console.log(
        `  Claude CLI not available. Falling back to template for ${featureKey}.`
      );
      return generateSpecContent(featureKey);
    }

    console.log(
      `Generating source-aware test for ${featureKey} via Claude CLI...`
    );
    const claudeOutput = generateWithClaude(featureKey, feature);
    if (claudeOutput) {
      console.log(`  Source-aware test generated successfully for ${featureKey}.`);
      return claudeOutput;
    }
    console.log(`  Falling back to template for ${featureKey}.`);
  }

  return generateSpecContent(featureKey);
}

// ---------------------------------------------------------------------------
// --auto: Generate tests for ALL features missing test files
// ---------------------------------------------------------------------------
if (hasFlag("--auto")) {
  fs.mkdirSync(TESTS_DIR, { recursive: true });

  const results = {
    scanned: 0,
    created: [],
    createdWithClaude: [],
    alreadyExist: [],
    claudeFallbacks: [],
  };

  for (const featureKey of Object.keys(manifest.features)) {
    results.scanned++;
    const slug = featureKey.replace(/_/g, "-");
    const specPath = path.join(TESTS_DIR, `${slug}.spec.ts`);

    if (fs.existsSync(specPath)) {
      results.alreadyExist.push(featureKey);
      continue;
    }

    const content = generateSpec(featureKey);
    fs.writeFileSync(specPath, content);
    results.created.push(featureKey);

    // Track whether Claude was used or template fallback
    if (CLAUDE_MODE && content !== generateSpecContent(featureKey)) {
      results.createdWithClaude.push(featureKey);
    } else if (CLAUDE_MODE) {
      results.claudeFallbacks.push(featureKey);
    }
  }

  if (JSON_MODE) {
    console.log(JSON.stringify(results, null, 2));
  } else {
    console.log(`=== Auto-Generate Feature Tests ===\n`);
    console.log(`Scanned: ${results.scanned} features in manifest`);
    console.log(`Already exist: ${results.alreadyExist.length}`);
    console.log(`Created: ${results.created.length}`);
    if (CLAUDE_MODE) {
      console.log(
        `  - via Claude CLI: ${results.createdWithClaude.length}`
      );
      console.log(
        `  - template fallback: ${results.claudeFallbacks.length}`
      );
    }
    if (results.created.length > 0) {
      console.log(`\nNew test files:`);
      for (const f of results.created) {
        const slug = f.replace(/_/g, "-");
        const suffix = results.createdWithClaude.includes(f)
          ? " (claude)"
          : "";
        console.log(`  + e2e/tests/features/${slug}.spec.ts${suffix}`);
      }
    }
    console.log(`\nRun: cd e2e && npm run test:feature-tests`);
  }
  process.exit(0);
}

// ---------------------------------------------------------------------------
// --feature: Generate test for a single feature
// ---------------------------------------------------------------------------
const featureKey = getArg("--feature");
if (!featureKey) {
  console.error("Usage:");
  console.error(
    "  node scripts/e2e/generate-tests.js --feature <feature_key>"
  );
  console.error(
    "  node scripts/e2e/generate-tests.js --feature <key> --claude   # Source-aware"
  );
  console.error(
    "  node scripts/e2e/generate-tests.js --auto                     # All missing"
  );
  console.error(
    "  node scripts/e2e/generate-tests.js --auto --claude             # All missing (Claude)"
  );
  console.error(
    "  node scripts/e2e/generate-tests.js --auto --json               # JSON output"
  );
  console.error(
    "  node scripts/e2e/generate-tests.js --list                      # List features"
  );
  console.error(
    "  node scripts/e2e/generate-tests.js --from-spec <path|all>      # From spec doc"
  );
  console.error(
    "  node scripts/e2e/generate-tests.js --from-spec all --dry-run   # Preview spec tests"
  );
  process.exit(1);
}

const feature = manifest.features[featureKey];
if (!feature) {
  console.error(`Feature "${featureKey}" not found in manifest.json.`);
  console.error(
    `Available: ${Object.keys(manifest.features).join(", ")}`
  );
  process.exit(1);
}

// Ensure tests directory exists
fs.mkdirSync(TESTS_DIR, { recursive: true });

const slug = featureKey.replace(/_/g, "-");
const specPath = path.join(TESTS_DIR, `${slug}.spec.ts`);

if (fs.existsSync(specPath)) {
  console.log(`Test file already exists: ${specPath}`);
  console.log("Delete it first to regenerate.");
  process.exit(0);
}

// Write spec
const content = generateSpec(featureKey);
fs.writeFileSync(specPath, content);
console.log(`Created: ${specPath}`);

// Print checklist
const usedClaude =
  CLAUDE_MODE && content !== generateSpecContent(featureKey);
console.log("\nChecklist:");
console.log(
  `  [x] Test spec created at e2e/tests/features/${slug}.spec.ts${usedClaude ? " (source-aware via Claude)" : " (template)"}`
);
if (!usedClaude) {
  console.log(
    `  [ ] Review manifest.json personas for "${featureKey}"`
  );
  console.log(
    `  [ ] Verify permission expectations in manifest.json roles`
  );
}
if ((feature.pages || []).some((p) => p.includes("*"))) {
  console.log(
    `  [ ] Add MOC seed helpers for wildcard pages: ${feature.pages.filter((p) => p.includes("*")).join(", ")}`
  );
}
console.log(
  `  [ ] Run: cd e2e && npx playwright test tests/features/${slug}.spec.ts`
);
