/**
 * approval_mode_toggle — Auto-generated feature persona test
 *
 * Tests permissions, page access, and denial for all personas
 * mapped to this feature in manifest.json.
 *
 * Generated by: node scripts/e2e/generate-tests.js --feature approval_mode_toggle
 */

import { describeFeaturePersonaTests } from "../../templates/feature-persona.template";

describeFeaturePersonaTests("approval_mode_toggle");
