/**
 * dashboard_and_project_overview — Auto-generated feature persona test
 *
 * Tests permissions, page access, and denial for all personas
 * mapped to this feature in manifest.json.
 *
 * Generated by: node scripts/e2e/generate-tests.js --feature dashboard_and_project_overview
 */

import { describeFeaturePersonaTests } from "../../templates/feature-persona.template";

describeFeaturePersonaTests("dashboard_and_project_overview");
