/**
 * layer_5_paid_conversion — Auto-generated feature persona test
 *
 * Tests permissions, page access, and denial for all personas
 * mapped to this feature in manifest.json.
 *
 * Generated by: node scripts/e2e/generate-tests.js --feature layer_5_paid_conversion
 */

import { describeFeaturePersonaTests } from "../../templates/feature-persona.template";

describeFeaturePersonaTests("layer_5_paid_conversion");
