/**
 * layer_6_review_and_adjustment — Auto-generated feature persona test
 *
 * Tests permissions, page access, and denial for all personas
 * mapped to this feature in manifest.json.
 *
 * Generated by: node scripts/e2e/generate-tests.js --feature layer_6_review_and_adjustment
 */

import { describeFeaturePersonaTests } from "../../templates/feature-persona.template";

describeFeaturePersonaTests("layer_6_review_and_adjustment");
