/**
 * layer_1_idea_definition — Auto-generated feature persona test
 *
 * Tests permissions, page access, and denial for all personas
 * mapped to this feature in manifest.json.
 *
 * Generated by: node scripts/e2e/generate-tests.js --feature layer_1_idea_definition
 */

import { describeFeaturePersonaTests } from "../../templates/feature-persona.template";

describeFeaturePersonaTests("layer_1_idea_definition");
