/**
 * Auto-generated regression test for MOC build-approval_mode_toggle-1772577675178.
 * Verifies the fix for: Build feature: Approval Mode Toggle
 * Changed files: app/settings/page.tsx, lib/settings/index.ts
 * Generated by moc-auto-fix.js — do not edit manually.
 */

import { test, expect } from "../../fixtures/test";

test.describe("Regression: reg-build-approval_mode_", () => {
  test.beforeEach(async ({ sim }) => {
    await sim.loginAsDeveloper();
    await sim.simulateAs({
      role: "user",
      name: "low-risk",
    });
  });

  test("page loads without errors after fix", async ({ page, sim }) => {
    const consoleErrors: string[] = [];
    page.on("console", (msg) => {
      if (msg.type() === "error") {
        consoleErrors.push(msg.text());
      }
    });

    await sim.goto("/settings");
    await page.waitForLoadState("networkidle");

    // Verify page loaded
    const title = await page.title();
    expect(title).toBeTruthy();

    // Check no critical console errors
    const critical = consoleErrors.filter(
      (e) => !e.includes("Failed to fetch") && !e.includes("hydration")
    );
    expect(critical.length).toBe(0);

    await sim.recordGreenPass("reg-build-approval_mode_", ["app/settings/page.tsx","lib/settings/index.ts"]);
  });
});
