/**
 * Auto-generated regression test for MOC build-dashboard_and_project_overview-1772555869139.
 * Verifies the fix for: Build feature: Dashboard and Project Overview
 * Changed files: app/page.tsx
 * Generated by moc-auto-fix.js — do not edit manually.
 */

import { test, expect } from "../../fixtures/test";

test.describe("Regression: reg-build-dashboard_and_", () => {
  test.beforeEach(async ({ sim }) => {
    await sim.loginAsDeveloper();
    await sim.simulateAs({
      role: "user",
      name: "-engine",
    });
  });

  test("page loads without errors after fix", async ({ page, sim }) => {
    const consoleErrors: string[] = [];
    page.on("console", (msg) => {
      if (msg.type() === "error") {
        consoleErrors.push(msg.text());
      }
    });

    await sim.goto("/dashboard");
    await page.waitForLoadState("networkidle");

    // Verify page loaded
    const title = await page.title();
    expect(title).toBeTruthy();

    // Check no critical console errors
    const critical = consoleErrors.filter(
      (e) => !e.includes("Failed to fetch") && !e.includes("hydration")
    );
    expect(critical.length).toBe(0);

    await sim.recordGreenPass("reg-build-dashboard_and_", ["app/page.tsx"]);
  });
});
